# Generated by Django 4.0.4 on 2024-02-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_domain_remove_customuser_subscriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='txt_record',
            field=models.CharField(default='txt', max_length=255),
        ),
    ]
