# Generated by Django 4.0.4 on 2024-02-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_customuser_txt_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='recipients',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.domain'),
        ),
    ]
