# Generated by Django 4.0.4 on 2024-02-28 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_emailmessage_sendto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('txt_record', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('alt_users', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.virtualdomain')),
            ],
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='security_info',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
        migrations.DeleteModel(
            name='SecurityInfo',
        ),
    ]
