# Generated by Django 5.0.2 on 2024-02-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_virtualdomain_virtualuser_remove_emailmessage_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualdomain',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='virtualdomain',
            name='message_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
