# Generated by Django 5.0.2 on 2024-03-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_virtualdomain_message_virtualdomain_message_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('alt_users', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='VirtualDomain',
            new_name='VirtualDomains',
        ),
        migrations.DeleteModel(
            name='VirtualUser',
        ),
    ]
