# Generated by Django 5.0.2 on 2024-03-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_virtualusers_rename_virtualdomain_virtualdomains_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAliases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.IntegerField()),
                ('source', models.EmailField(max_length=254)),
                ('destination', models.EmailField(max_length=254)),
            ],
        ),
    ]
